services:
  postgres:
    container_name: pg-findAFriend
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=findAFriend
      - PGDATA=/data/postgres

volumes:
  pgdata:
