services:
  postgres:
    container_name: pg-findAFriend
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=findAFriend
      - PGDATA=/data/postgres

  redis:
    image: bitnami/redis:latest
    container_name: redis-findAFriend
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  pgdata:
  redis_data:
